### ISSUE TITLE
ImportError: cannot import name quote

### ISSUE THREAD

**Issue by husio** [maraujop/requests-oauth2#10]
```
Python 3.3.2 (default, Sep  6 2013, 09:30:10) 
[GCC 4.8.1 20130725 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Configuration loaded...
>>> from requests_oauth2 import OAuth2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[..]/python3.3/site-packages/requests_oauth2/__init__.py", line 1, in <module>
    from requests_oauth2.oauth2 import OAuth2
  File "[..]/python3.3/site-packages/requests_oauth2/oauth2.py", line 2, in <module>
    from urllib import quote, urlencode
ImportError: cannot import name quote
```

Version of libs:

```
pip list | grep request
requests (1.2.3)
requests-oauth2 (0.2.0)
requests-oauthlib (0.3.1)
```

**Comment by mani619cash** [comment]
what is solution of this error?

**Comment by rollcat** [comment]
grugnog's #11 solved this (thank you!). I've committed 0f7c8d2 to fix other Py3k issues. Closing.
